### ISSUE TITLE
Issue downloading anime on Ubuntu

### ISSUE THREAD

**Issue by mglaserg** [KorigamiK/kickassanime-downloader#3]
So I was trying to download Vivy Flourite Eye's Song EP 10 and I got this error:

> [vivy fluorite eyes song ep_10.mp4] stderr: bash: -c: line 0: unexpected EOF while looking for matching ''

> [vivy fluorite eyes song ep_10.mp4] stderr: bash: -c: line 1: syntax error: unexpected end of file

I was wondering if I did something wrong here

**Comment by KorigamiK** [comment]
Could you send the log of the complete error. That would be great

**Comment by KorigamiK** [comment]
So, I've caught to bug. Please pull the latest changes in the repository. I am going to add a workflow to make releases automatically so it's a little more convenient for users to download the releases. 

Since you are on linux, it would be better for you to use aiodownloader instead of subprocess although both should work. You can change your `config.json` like this:
```
{
    ...
    "not used downloader": "subprocess",
    "downloader": "aiodownloader",
    ...
}
``` 

Here's the expected behavior to download the episode. 
![vivy trailer](https://user-images.githubusercontent.com/72932688/122814235-89748c00-d2f1-11eb-8889-eddaad975c23.gif)

Let me know if you are still facing errors : )

**Comment by mglaserg** [comment]
It seems to work now! I was able to download EP 10, however I didn't see an option to change the resolution. I don't know if that' s something else you would want to take a look at. 

Thank you for help on this though!

**Comment by KorigamiK** [comment]
Hey, I'm glad to hear that. I finally remembered to update the readme for this project thanks to you. [You can check it out](https://github.com/KorigamiK/kickassanime-downloader/blob/master/README.md) and see if you find anything useful. 

I think I haven't explained the quality selection right now but basically it is in the order  that appears on the website. For example in `./Config/config.json` the numbers for each of the servers refer to the qualities in the order in which they appear so, 
for `KICKASSANIMEX` for example the numbers would refer to the qualities like this:  
![quality](https://user-images.githubusercontent.com/72932688/119536658-f1918a00-bda6-11eb-9599-89b2973c1803.jpg)

I'll add this to the readme.

**Comment by KorigamiK** [comment]
Added the config section in readme!

**Comment by mglaserg** [comment]
Thank you!! I love this project by the way
