### ISSUE TITLE
'No such file or directory' error

### ISSUE THREAD

**Issue by Boscik** [KorigamiK/kickassanime-downloader#6]
Hi, when I try to download any anime I get error 'No such file or directory'.

![image](https://user-images.githubusercontent.com/96445088/146825874-5464ba4e-d801-4408-95ec-a89c8e37019a.png)

I've tried editing the download folder and it should be okay.
Also even when I change server priorities it always tries to download from beststremo.

This issue might be caused by my bad installation or set up, I've downloaded the tool today.

**Comment by KorigamiK** [comment]
I see the error. It may be because you have not set the download location in `to_update.json` to your preference. 

I understand this unexpected crash and it will be fixed in the next update.

As for the server, it is not `beststremo`, the server is `html5` as you can see. It should be in accordance to your server preferences. Notify me if it's not.

**Comment by Boscik** [comment]
I apologize, the home folder wasn't set properly. The path wasn't correct.
It seems to be working now.
